# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170828_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.ImageField(upload_to='static/image/', verbose_name='头像'),
        ),
    ]
